### ISSUE TITLE
Gradle plugin update required

### ISSUE THREAD

**Issue by Harishwarrior** [alhappler/alh_pdf_view#51]
We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34
Update Gradle property to suppress warning
Affected Modules: alh_pdf_view_android

**Comment by andreBalh** [comment]
Hello @Harishwarrior 
Which version do you use of this package? Probably you have to update to the version `2.0.0` because the newest version runs also on `34`.
And if this isn't fixing your issue, can you send me the report of `flutter doctor -v`?

**Comment by Harishwarrior** [comment]
> We recommend using a newer Android Gradle plugin to use compileSdk = 34

```
We recommend using a newer Android Gradle plugin to use compileSdk = 34
```

As the error says we need to update grade plugin to 8.0x currently it is 7.x to be compatible with compile sdk 34

**Comment by andreBalh** [comment]
Can you send me the report of `flutter doctor -v`? @Harishwarrior

**Comment by andreBalh** [comment]
I tried this with the example app and cannot reproduce the issue. Did you try `flutter pub upgrade`? Probably the app is still running with an older version. @Harishwarrior

**Comment by Harishwarrior** [comment]
Open the android folder in Android studio. Select Build -> Clean and then select Rebuild project.

My pubspec.lock file

```
  alh_pdf_view:
    dependency: "direct main"
    description:
      name: alh_pdf_view
      sha256: "120e340eb3c7102db9a9851ff0d739267c335f755c2296553fe9dc96cc5d0947"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
  alh_pdf_view_android:
    dependency: transitive
    description:
      name: alh_pdf_view_android
      sha256: "56b4e0200a522ba4f7703e367bc05d9965ce1cf9c0478cffe6c86df34c1a9e94"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
  alh_pdf_view_ios:
    dependency: transitive
    description:
      name: alh_pdf_view_ios
      sha256: b7f3bc94188536c350d9a7d3ecaf8d568d77dc6338dd647753bd1b69908fc63f
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
  alh_pdf_view_platform_interface:
    dependency: transitive
    description:
      name: alh_pdf_view_platform_interface
      sha256: "44defb6a34e1243449f0ab7b1e3447d652bd25809bc6560a3289a03b56a1dde1"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
```
